/* Gerado por build_extension.py — conteúdo oficial do criador (tradução PT-BR),
 * extraído do codex da storyline via API. Não editar à mão; regenere. */

export const FORGE = { design: "VERBO CONCRETO + ALVO CONCRETO + RESULTADO CONCRETO + CUSTO / CONDIÇÃO / LIMITE REAIS.", low: "Habilidades de nível baixo geralmente devem usar um ou mais dos seguintes:\n\nsacrifício de recursos\nrepercussão tardia\nmaldição temporária\nfraqueza corporal\ndestruição de itens\npré-requisito perigoso\ndependência ambiental\ndor ou ferimento\nexposição social\nalvo restrito\narmazenamento limitado\nrequisito biológico desconfortável\n\nA desvantagem deve importar.\n\nO benefício ainda deve fazer o jogador querer experimentá-la.",
  tiers: {
    "F": "Uma maldição, barganha perigosa ou troca severa que ainda cria um exploit tentador ou um estilo de jogo incomum.",
    "E": "Doloroso ou inconveniente, mas estrategicamente útil quando manuseado de forma inteligente.",
    "D": "Uma ferramenta útil e estranha com uma limitação, custo ou requisito de preparação sério.",
    "C": "Forte o suficiente para sustentar uma build reconhecível ou estratégia recorrente.",
    "B": "Um componente de build importante que muda escolhas de equipamento, combate, exploração, criação ou progressão.",
    "A": "Excepcionalmente poderoso. Uma estratégia primária pode girar em torno dele.",
    "S": "Deliberadamente overpowered para os padrões normais e capaz de mudar como toda a run é jogada.",
    "SS": "Concede acesso a algo que quase ninguém em Veyrath pode reproduzir.",
    "SSS": "Quebra ou contorna uma regra normal do mundo de forma concreta e explorável.",
    "SSS+": "Anomalia definidora de campanha. Todo o ciclo de progressão pode girar em torno dela.",
  },
};

export const RACE_RULES = "# REGRAS DA ROLETA DE RAÇA\n\nA Roleta de Raça determina a raça reencarnada de {{user}} e a linha de base biológica.\n\nAntes de rolar, {{user}} pode permanecer Humano. Isso pula a Roleta de Raça e não gasta nenhuma Rolagem Compartilhada.\n\nA raça afeta atributos, aparência, sentidos, biologia, compatibilidade de equipamento e complicações sociais plausíveis. Ela nunca determina personalidade, moralidade, inteligência, sexualidade, lealdade, romance ou destino.\n\nApenas Humano é totalmente linha de base. Raças não humanas exigem forças e desvantagens significativas.\n\nA Rolagem de Dados determina a raridade usando o Prompt de Funções. Após a raridade ser conhecida, leia a entrada correspondente do Conjunto de Raças e selecione/role um resultado elegível.\n\nO catálogo é inspirador em vez de absolutamente exaustivo: uma nova raça pode ser gerada apenas se claramente se encaixar na raridade rolada, em Veyrath e nos mesmos padrões de equilíbrio.\n\nCada resultado mostra:\nRaça; Raridade; Mudanças de Atributos; Forças; Fraquezas; Complicação Social; Rolagens Compartilhadas Restantes.\n\nUma vez aceito, Atributos do Personagem possui Raça, Traços Raciais, Fraquezas Raciais e mudanças de atributos resultantes.\n\nUma rolagem descarta permanentemente o resultado atual.";

export const RACE_POOLS = {
  "Comum": "Humano — nenhum. Flexível, aceito, linha de base.\nForasteiro Meio-Humano — SORTE +1, SAB -1. Adaptável; socialmente incerto.\nBeastkin Felino — DES +2, SAB +1, FOR -1. Ágil; audição sensível.\nBeastkin Canino — CON +1, SAB +1, DES +1, INT -1. Rastreamento/resistência; sensibilidade a cheiros.\nAnão — CON +2, FOR +1, DES -1. Durável/criação; lento.\nMeio-Elfo — INT +1, SAB +1. Sentido de mana/aprendizado; tratamento de forasteiro.",
  "Incomum": "Beastkin Lobo — FOR +1, DES +1, SAB +2, INT -1. Rastreamento; suspeita.\nBeastkin Raposa — DES +1, INT +1, SORTE +1, CON -1. Astuto/furtivo; desconfiado.\nBeastkin Coelho — DES +3, SAB +1, FOR -1, CON -1. Muito rápido; frágil.\nBeastkin Urso — FOR +2, CON +2, DES -1, INT -1. Poderoso/resistente; furtividade ruim.\nElfo — DES +1, INT +2, CON -1. Afinidade/precisão com mana; frágil.\nSangue de Orc — FOR +2, CON +1, INT -1. Forte/resistente; preconceito.\nGoblin-Kin — DES +2, SORTE +1, FOR -1, CON -1. Pequeno/sorrateiro; preconceito severo.\nKobold — DES +1, CON +1, SAB +1, FOR -1. Senso de túnel; fisicamente fraco.",
  "Raro": "Beastkin Serpente — DES +1, SAB +2, CON -1. Sentido de calor/resistência a veneno; sensível ao frio.\nSangue de Dríade — SAB +2, CON +1, FOR -1. Sentido de planta/afinidade herbal; vulnerável a fogo.\nSangue de Povo do Mar — SAB +1, CON +1, DES +1, FOR -1. Afinidade aquática; fraqueza a calor seco.\nSangue de Lamia — DES +1, SAB +1, CON +1, FOR -1. Flexível/resistente a veneno; problemas com armadura.\nSangue de Harpia — DES +2, SAB +1, CON -1. Visão afiada/sentido de vento; frágil.\nSangue de Minotauro — FOR +3, CON +1, DES -1, INT -1. Poderoso; grande/conspícuo.\nSangue de Aasimar — SAB +2, SORTE +1, DES -1. Ressonância sagrada; atenção da igreja.\nSangue de Tiefling — INT +1, DES +1, SORTE +1, SAB -1. Afinidade com maldição; suspeita sagrada.",
  "Muito Raro": "Sangue de Gigante — FOR +3, CON +2, DES -2, INT -1. Força enorme; equipamento caro.\nSangue de Dragonkin — FOR +2, CON +2, SAB -1, SORTE -1. Poderoso; conspícuo.\nShadowkin — DES +2, INT +1, CON -1. Afinidade com furtividade; fraqueza a luz sagrada.\nNascido da Pedra — CON +3, FOR +1, DES -2. Extremamente resistente; pesado/lento.\nTocada por Fadas — SORTE +2, DES +1, CON -1, SAB -1. Sorte estranha; interações mágicas instáveis.\nMarcada pelo Sol — FOR +1, CON +1, SAB +1, DES -1. Afinidade com calor/radiância; marcas visíveis.",
  "Aben\u00e7oado": "Abençoado pela Alvorada — SAB +2, CON +1, SORTE -1. Resistência à corrupção/recuperação solar; interesse da igreja.\nAbençoado pelas Estrelas — INT +2, SORTE +1, CON -1. Percepção cósmica; sensibilidade a anomalias.\nSangue de Santo — SAB +2, SORTE +1, FOR -1. Afinidade sagrada/curativa; expectativas religiosas.\nAbençoado pelo Bosque — SAB +2, CON +1, DES -1. Afinidade com a natureza; fraqueza a pragas/fogo.\nAbençoado pela Tempestade — DES +2, SAB +1, CON -1. Afinidade com clima/relâmpagos; instabilidade de tempestade.\nAbençoado pela Lua — SAB +2, DES +1, FOR -1. Afinidade com noite/sonhos; limites lunares.\nAbençoado pelo Sol — FOR +1, CON +1, SAB +1, DES -1. Afinidade com radiância/calor; marcas óbvias.\nAbençoado pelo Lar — CON +2, SAB +1, SORTE -1. Recuperação/proteção; expectativas sociais.\nAbençoado pela Misericórdia — SAB +3, FOR -1, CON -1. Cura/suporte; sensibilidade à dor.\nAbençoado pelo Juramento — FOR +1, SAB +2, SORTE -1. Benefícios de votos cumpridos; votos quebrados o enfraquecem.",
  "\u00c9pico": "Nascido Vampiro — DES +2, INT +1, CON +1, SAB -1. Força noturna; fome de sangue/perigo sagrado.\nQuimérico — FOR +1, DES +1, CON +1, SORTE +1, INT -1. Adaptativo; biologia instável.\nLigado ao Espírito — SAB +3, INT +1, CON -2. Percepção espiritual; corpo frágil.\nHomúnculo — INT +2, CON +1, SORTE -2. Corpo artificial; perigo de identidade/legal.\nBoneca Viva — CON +2, INT +1, SAB -1, SORTE -1. Reparável; estranho.\nSangue de Revenant — CON +2, SAB +1, SORTE -2. Resistência à morte; desconforto sagrado.\nNascido da Maldição — INT +1, SAB +1, SORTE +2, CON -2. Interação com maldição; atrai infortúnio.\nHíbrido de Spectro de Mana — INT +3, DES +1, CON -2. Percepção extrema de mana; corpo instável.",
  "Lend\u00e1rio": "Tocado pelo Vazio — INT +2, SAB +2, SORTE -2, CON -1. Afinidade com anomalias; atenção perigosa.\nErro Celestial — SORTE +3, SAB +1, FOR -1, CON -1. Ressonância Divina/Sistema; leituras anormais.\nAasimar Caído — SAB +2, INT +1, SORTE +1, CON -1. Poder sagrado quebrado; obsessão da igreja.\nHerdeiro Abissal — FOR +1, INT +2, CON +1, SORTE -2. Resistência ao abismo; hostilidade sagrada.\nSangue Antigo — FOR +1, DES +1, CON +1, INT +1, SAB +1, SORTE -2. Ressonância com relíquias; atrai mecanismos antigos.",
  "M\u00edtico": "Humano Exaltado — FOR +1, DES +1, CON +1, INT +1, SAB +1, SORTE +1. Linha de base excepcional; interesse de facções.\nBeastkin Exaltado — DES +3, SAB +2, FOR +1, CON -1. Sentidos supremos; sobrecarga sensorial.\nElfo Exaltado — INT +3, SAB +2, DES +1, CON -2. Afinidade extrema com mana; frágil.\nDragonkin Exaltado — FOR +3, CON +3, INT +1, SORTE -2. Grande poder; impossível de esconder.\nHomúnculo Exaltado — INT +3, CON +2, DES +1, SORTE -3. Corpo artificial excepcional; atenção de anomalias.\nFragmento Primordial — FOR +1, DES +1, CON +1, INT +2, SAB +2, SORTE -3. Ressonância antiga; atrai coisas seladas.\nErro de Impressão Divino — SORTE +4, INT +1, SAB +1, CON -2. Sorte impossível; atenção divina.",
  "Amaldi\u00e7oado": "Vaso Quebrado — INT +2, SAB +2, CON -3. Alta percepção; extremamente frágil.\nHollowkin — DES +1, SAB +1, SORTE +1, FOR -1, CON -1. Presença baixa; vitalidade fraca.\nNascido de Vidro — INT +2, DES +1, CON -3. Clareza de mana; extremamente frágil.\nCinzento — CON +1, SAB +1, SORTE -2. Sobrevivência em ruínas; tratado como mau presságio.\nNascido do Lodo — CON +2, SAB +1, DES -1, SORTE -1. Resistência a veneno; aura desagradável.\nSangue Pálido — DES +2, INT +1, CON -2, SORTE -1. Movimento silencioso; cura ruim.",
};

export const ENTRY_RULES = "# CATÁLOGO DE ENTRADA NO MUNDO\n\nA Entrada no Mundo define região, localização, dificuldade, evento inicial e pressão imediata. A Rolagem de Dados determina a dificuldade usando o Prompt de Funções; então selecione ou role um cenário elegível dessa dificuldade.";

export const ENTRY_SCENARIOS = {
  "F": [{name:"ESTRADA DE WHITEBROOK", region:"Caldris", desc:"Estrada rural segura perto da civilização; sem identidade, contatos ou dinheiro."}],
  "E": [{name:"CHEGADA À GUILDA DE LYRHAVEN", region:"Caldris", desc:"Correria de contratos da guilda; civilização por perto, mas sem identidade ou reputação."}],
  "D": [{name:"ESTRADA DE CARAVANA DANIFICADA", region:"Caldris", desc:"Viajantes feridos, pessoas desaparecidas e perigo de monstros próximo."}, {name:"ERRO DE REGISTRO EM MERROWSPIRE", region:"Veloria", desc:"Registro institucional expõe um perfil anormal."}],
  "C": [{name:"BORDA DA FLORESTA AO ANOITECER", region:"Caldris", desc:"Floresta Greenbriar sob luz desvanecente; segurança da estrada deteriorando."}, {name:"ROTA DE EXPLORAÇÃO FRACASSADA", region:"Caldris", desc:"Sangue, rastros, equipamento abandonado e perigo não resolvido."}, {name:"DISTÚRBIO NO MERCADO DE RELÍQUIAS", region:"Veloria", desc:"Uma relíquia instável é ativada em meio a testemunhas e salvamento valioso."}, {name:"INCIDENTE NA ACADEMIA", region:"Veloria", desc:"Acidente mágico, pesquisadores e resíduo perigoso."}, {name:"PROCISSÃO DO INQUISIDOR", region:"Aurelian", desc:"Instrumentos de detecção religiosa reagem de forma anormal."}, {name:"COLAPSO EM PASSAGEM DE MONTANHA", region:"Kharzug", desc:"Um colapso bloqueia a rota normal de montanha."}, {name:"CAOS NO CAIS DE BLACKWATER", region:"Sable Coast", desc:"Confusão violenta no porto e interesses concorrentes."}],
  "B": [{name:"ECO DO PINÁCULO CAÍDO", region:"Caldris", desc:"Anomalia mágica antiga com ruínas instáveis e interesse de aventureiros."}, {name:"VIOLAÇÃO DE ARQUIVO RESTRITO", region:"Veloria", desc:"Aparece perto de arquivos restritos enquanto alarmes de segurança estão ativos."}, {name:"DISTÚRBIO NA CATACUMBA", region:"Aurelian", desc:"Atividade de mortos-vivos aumenta abaixo de Saint Oravel."}, {name:"DESCOBERTA DE COFRE SELADO", region:"Kharzug", desc:"Cofre antigo abre enquanto grupos concorrentes convergem."}, {name:"IDENTIDADE ERRADA DE CONTRABANDISTA", region:"Sable Coast", desc:"Confundido com um mensageiro ou comprador criminoso esperado."}, {name:"RESCALDO DE ATAQUE PIRATA", region:"Sable Coast", desc:"Baixas, roubo e perseguição ativa ao redor do porto."}],
  "A": [{name:"MANIFESTAÇÃO EM RITUAL DA IGREJA", region:"Aurelian", desc:"Aparece dentro de um ritual sagrado e é imediatamente examinado."}, {name:"VIOLAÇÃO NA MINA DE DEEPGATE", region:"Kharzug", desc:"Trabalhadores fogem de criaturas hostis emergindo do subsolo."}, {name:"PORTÃO DE QUARENTENA DE PRAGA", region:"Sable Coast", desc:"Dentro de um distrito de quarentena controlado com saídas restritas."}, {name:"POSTO AVANÇADO DE REDMIRE APÓS ATAQUE", region:"Redmire", desc:"Defesas danificadas, refugiados e suprimentos escassos."}, {name:"ATAQUE A COLUNA DE REFUGIADOS", region:"Redmire", desc:"Criaturas hostis se aproximam de uma coluna vulnerável de refugiados."}],
  "S": [{name:"BORDA DE MASMORRA EM MUTAÇÃO", region:"Redmire", desc:"Uma masmorra supostamente de baixo nível está mudando violentamente."}, {name:"SURGIMENTO PERDIDO EM BLOODFEN", region:"Redmire", desc:"Sozinho em pântano perigoso longe de civilização confiável."}, {name:"LIMIAR DE RUÍNA SELADA", region:"Desconhecido", desc:"Irregularidade do Sistema ao lado de uma ruína além das expectativas de iniciantes."}],
  "SS+": [{name:"LADO ERRADO DA FRONTEIRA", region:"Território de Monstros", desc:"Território hostil profundo; a sobrevivência depende de evasão, ocultação ou perturbação extraordinária."}],
};

export const ALIGNMENT_CATALOGUE = "# CATÁLOGO DE ALINHAMENTO INICIAL\n\nAlinhamentos Iniciais são pacotes para iniciantes destinados a adultos reencarnados que não possuem treinamento infantil de Veyrath e experiência profissional local.\n\nEles não são classes verdadeiras.\n\nEles não aumentam o Nível, não modificam atributos básicos, não garantem maestria, não bloqueiam crescimento futuro nem impedem o aprendizado de caminhos não relacionados.\n\n{{user}} escolhe o Alinhamento; ele não é atribuído aleatoriamente a menos que explicitamente solicitado.\n\n## VANGUARDA NOVATA\nSobrevivência na linha de frente, manejo básico de armas, proteção e confiança física.\nPacote típico: uma Habilidade básica defensiva/de combate, proficiência marcial Familiar, arma branca simples e equipamento de proteção básico.\n\n## EXPLORADOR NOVATO\nFurtividade, mobilidade, observação, rastreamento e consciência de rotas.\nPacote típico: uma Habilidade ou Passiva básica de movimento/exploração, proficiência Familiar em furtividade/rastreamento, arma leve e equipamento de viagem prático.\n\n## CONJURADOR APRENDIZ\nControle de mana, fundamentos de conjuração segura e teoria mágica básica.\nPacote típico: uma Magia de Nível 1, proficiência Familiar em conjuração e um foco de conjuração simples.\n\n## CURADOR INICIANTE\nPrimeiros socorros, avaliação de ferimentos e suporte básico mágico ou mundano.\nPacote típico: uma habilidade básica de cura/suporte, proficiência Familiar em primeiros socorros e um pequeno kit médico.\n\n## DUELISTA ERRANTE\nPrecisão, trabalho de pés, timing e técnica com armas leves.\nPacote típico: uma Habilidade básica de mobilidade ou precisão, proficiência Familiar em lâminas leves e uma arma leve adequada.\n\n## CAÇADOR SELVAGEM\nSobrevivência, rastreamento, caça, fundamentos de combate à distância e habilidades de campo.\nPacote típico: uma Habilidade ou Passiva básica de caça/combate, proficiência Familiar em sobrevivência e arco, lança ou equipamento de campo equivalente.\n\n## MEXEDOR DE RELÍQUIAS\nFerramentas, avaliação, salvamento, reparo simples e curiosidade em relação a objetos mágicos.\nPacote típico: uma habilidade básica de avaliação/criação, proficiência Familiar em ferramentas e um kit de ferramentas compacto.\n\n## ACÓLITO VIAJANTE\nCultura de fé, proteções, perigo espiritual e resistência sobrenatural.\nPacote típico: uma habilidade básica de proteção/suporte, proficiência Familiar religiosa/proteção e um foco devocional ou de proteção simples.\n\nQuando um Alinhamento é finalizado, Atributos do Personagem possui o Alinhamento Inicial selecionado, Habilidades concedidas e Inventário concedido.\n\nEspecializações posteriores derivam do comportamento e desenvolvimento reais, e não apenas desta escolha inicial.";
